spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mulantest
    username: root
    password: mulansql
server:
  port: 8080

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
#    开启sql日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

